# Site settings
site: tech blog
title: woody's tech blog
keywords: woody, blog
description: >-
  woody's tech blog
lang: ko-KR
timezone:  Asia/Korea
repo: https://github.com/yuuisang # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: EuiSang Yu
  bio: Web Developer <br> company @trans-cosmos <br> stack @Java @Javascript @linux
  picture: assets/images/profile.png 
  github: yuuisang # github username
  twitter: onepase # twitter username
  facebook: onepase # facebook username
  instagram: onepase # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  youtube: https://www.youtube.com/ # youtube username
  linkedin: clothes.yoo # linkedin username
  email: clothes.yoo@gmail.com # email adress


# URL settings
#url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
url: "https://yuuisang.github.io/"
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false